# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4191bd8bd68c8362964ab8234b47f916637eeb0af1d36598fe031e988a05925f795e748e94237a7eb5752292047a78542917f98e965608417ae2d79fbaaaac42

test:
  secret_key_base: 023c491d332bdb45a4570278b88a4646770840d769e1ef7eb3c0f34abab218dd9d6155fb9377ec623318a94ef6a8cb52aa86c802c610d2a97897d544ed0175fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
